version: '3.9'

services:
  mysql-db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data-wrapd_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wrapd_testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  db-data-wrapd_postgresql:
    driver: local
  db-data-wrapd_mysql:
    driver: local
