- CREATE TABLE $$tester01 (x INT NOT NULL PRIMARY KEY, y INT NOT NULL)
- CREATE TABLE $$tester02 (a INT NOT NULL PRIMARY KEY, b INT NOT NULL)

- ALTER TABLE $$tester01 ADD z VARCHAR(20)
- ALTER TABLE $$tester02 ADD c VARCHAR(40)

- RENAME TABLE $$tester01 TO $$XYZ
- RENAME TABLE $$tester02 TO $$ABC
