/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.reldb.wrapd.demo.app;

import org.junit.jupiter.api.Test;
import org.reldb.wrapd.demo.Application;

class ApplicationTest {
    @Test
    void canRun() throws Exception {
        Application.main(new String[] {"test"});
    }
}
